[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
    let g:lsp_settings_servers_dir = '/Users/nami/.local/share/vim-lsp-settings/servers' 
'''
[[plugins]]
repo = 'cohama/lexima.vim'





