[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
    let g:denops_disable_version_check = 1
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
    function s:client_capabilities(server_info) abort
        let l:client_capabilities = lsp#default_get_supported_capabilities('a:server_info')
        let l:client_capabilities['textDocument']['completion']['completionItem']['snippetSupport'] = v:true
        return l:client_capabilities
    endfunction

    let g:lsp_get_supported_capabilities = [function('s:client_capabilities')]
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
    let g:lsp_settings_servers_dir = '~/.local/share/vim-lsp-settings/servers' 
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = "vim-skk/skkeleton"
hook_add = '''
call skkeleton#config({
\   'globalDictionaries': ['~/.skk/SKK-JISYO.L']
\})

call skkeleton#register_kanatable('rom',{
\   ',': ['，'],
\   '.': ['．']
\})
'''

[[plugins]]
repo = "altercation/vim-colors-solarized"
hook_add = '''
    syntax enable
    set background=dark
    colorscheme solarized
    call togglebg#map("<F5>")
'''

