[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
    let g:lsp_text_edit_enabled = 1
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
    let g:lsp_settings_servers_dir = '~/.local/share/vim-lsp-settings/servers' 
'''

[[plugins]]
repo = "altercation/vim-colors-solarized"
hook_add = """
	call togglebg#map("<F5>")	
	syntax enable
	colorscheme solarized
"""

[[plugins]]
repo = "vim-skk/skkeleton"
#hook_add = """
#    call skkeleton#config({ 'globalJisyo': '~/.skk/SKK-JISYO.L' })
#"""
hook_add = """
call skkeleton#config({
\   'globalDictionaries': ['~/.skk/SKK-JISYO.L']
\})

call skkeleton#register_kanatable('rom',{
\   ',': ['，'],
\   '.': ['．']
\})
"""
[[plugins]]
repo = 'hrsh7th/vim-vsnip'
